on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - run: sbt -v
           scalafmtCheckAll
           scalafmtSbtCheck
           warningsAll
    - if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
      uses: actions/upload-artifact@v3
      with:
        name: warnings.json
        path: target/warnings/warnings.json
    - if: github.event_name == 'pull_request'
      uses: dawidd6/action-download-artifact@v2
      with:
        path: target/warnings/warnings-previous.json
    - if: github.event_name == 'pull_request'
      run: sbt warningsDiff
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const diff = fs.readFileSync("target/warnings/warnings-diff.json").toString();
          const body = "warnings diff\n\n```json\n" + diff + "\n```";
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
